### ISSUE TITLE
Make a pip package

### ISSUE THREAD

**Issue by sergei-bondarenko** [ben-arnao/StoRM#3]
Please, make a pip package so it can be installed via pip as a dependency for projects. You can use github Actions for this and refer to my project as an example: https://github.com/sergei-bondarenko/xchg/blob/master/.github/workflows/push_to_master.yml

**Comment by ben-arnao** [comment]
@sergei-bondarenko Thank you for the feedback. I have made a pip package for this project. Please test and let me know if you have any issues. Thanks!
