### ISSUE TITLE
Potential Documentation Bug

### ISSUE THREAD

**Issue by SAH-UJA** [ben-arnao/StoRM#8]
I installed storm-tuner on colab but couldn't import Tuner class using:
`from storm.tuner import Tuner`
as mentioned in the PyPi docs

On referring the git repo, I could resolve it. I am now using:
`from storm_tuner import Tuner`

Also, `params` is not defined in the following code snippet (available in PyPi):
`from storm.tuner import Tuner

class MyTuner(Tuner):

    def run_trial(self, trial, *args):
        # retrieve hyperparameters
        hp = trial.hyperparameters

        # retrieve any parameters supplied via main search method
        X_train, y_train, X_test, y_test = args[0], args[1], args[2], args[3]

        # build our configuration
        model = self.build_fn(hp)

        # train model
        history = model.fit(X_train,
                            y_train,
                            epochs=25,
                            validation_data=(X_test, y_test),
                            batch_size=params['batch_size'])

        # calculate score
        score = history.history['val_loss'][-1]

        # assign score to the trial
        self.score_trial(trial, score)`

I tweaked this by following the repo examples and changed it to:
`batch_size = hp.Param('batch_size', [8,16,32])`

**Comment by ben-arnao** [comment]
Thank you very much for pointing that out! This is changed now.
